version: '3.9'

services:
  app:
    env_file:
      - .env
    image: my-rss-docker
    build: .
    volumes: 
      - ./src:$SRC_VOLUME
      - ./logs:$LOGS_VOLUME
    ports:
      - "$PORT:$PORT"
    command: npm run dev
