version: '3.9'

services:
  app:
    env_file:
      - .env
    image: my-rss-docker
    build: .
    volumes:
      - /usr/app
      - /usr/app/node_modules
    ports:
      - "$PORT:$PORT"
    command: npm run dev
