version: '3.9'

services:
  database:
    env_file:
      - .env
    image: postgres:alpine
    networks:
      - custom
    volumes:
      - databsedata:$DATABASE_VOLUME
    ports:
      - 11543:$DATABASE_PORT
    expose:
      - "$DATABASE_PORT"
    hostname: postgres
    environment:
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD
      - POSTGRES_USER=$DATABASE_USER
      - POSTGRES_DB=test
    deploy:
      restart_policy:
        condition: on-failure
  app:
    env_file:
      - .env
    image: my-rss-docker
    networks:
      - custom
    depends_on:
      - database
    build: .
    volumes:
      - logs:$LOGS_VOLUME
      - .:$SRC_VOLUME
    ports:
      - "$PORT:$PORT"
    deploy:
      restart_policy:
        condition: on-failure
    command: npm run dev
networks:
  custom:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: 'true'
volumes:
  logs:
  databsedata: