version: '3.9'

services:
  app:
    env_file:
      - .env
    image: my-rss-docker
    build: .
    volumes:
      - logs:$LOGS_VOLUME
      - .:$SRC_VOLUME
    ports:
      - "$PORT:$PORT"
    command: npm run dev
volumes:
  logs: